exports.addCategory = require('./post/addCategory')
exports.getCategories = require('./get/getCategories')
exports.addSubCategory = require('./post/addSubCategory')
exports.changeCategory = require('./put/changeCategory')
exports.changeSubcategory = require('./put/changeSubCategory')
exports.confirmSubCategory = require('./put/confirmSubCategory')
exports.confirmCategory = require('./put/confirmCategory')