const router = express.Router()
const verify = require('../../middleware/verify')

const zvonobot = require('./controllers/post/zvonobot')
const addNewCall = require('./controllers/post/addNewCall')
const search = require('./controllers/post/searchCall')
const getCold = require('./controllers/get/Cold')
const getHot = require('./controllers/get/Hot')
const getCalls = require('./controllers/get/Calls')
const getBasket = require('./controllers/get/getBasket')
const putCall = require('./controllers/put/changeCall')
const replacebasket = require('./controllers/put/replaceBasket')
const deleteCallBasket = require('./controllers/delete/deleteCallBusket')
const reminder = require('./controllers/post/reminder')
const changeStatus = require('./controllers/put/changeStatus')
const changeType = require('./controllers/put/changeType')

router  .post('/addcalls', zvonobot)
        .use(verify)
        .post('/addnewcall', addNewCall)
        .post('/searh', search)
        .post('/remind/:id', reminder)
        .get('/get/calls/:skip/:pagination', getCalls)
        .get('/get/calls/hot/:skip/:pagination', getHot)
        .get('/get/calls/cold/:skip/:pagination', getCold)
        .get('/get/baskets/:skip/:pagination', getBasket)
        .put('/changecall/:id', putCall)
        .put('/replacebasket/:id', replacebasket)
        .put('/changestatus/:id', changeStatus)
        .put('/changetype/:id', changeType)
        .delete('/delete/callbasket/:id', deleteCallBasket)

module.exports = router